INSERT INTO area (name) VALUES ('Administração');
INSERT INTO area (name) VALUES ('Agricultura');
INSERT INTO area (name) VALUES ('Arquitetura');
INSERT INTO area (name) VALUES ('Artes');
INSERT INTO area (name) VALUES ('Atendimento ao Cliente');
INSERT INTO area (name) VALUES ('Big Data');
INSERT INTO area (name) VALUES ('Biologia');
INSERT INTO area (name) VALUES ('Biotecnologia');
INSERT INTO area (name) VALUES ('Cloud Computing');
INSERT INTO area (name) VALUES ('Ciência de Dados');
INSERT INTO area (name) VALUES ('Comércio Exterior');
INSERT INTO area (name) VALUES ('Comunicação');
INSERT INTO area (name) VALUES ('Contabilidade');
INSERT INTO area (name) VALUES ('Consultoria');
INSERT INTO area (name) VALUES ('Criatividade');
INSERT INTO area (name) VALUES ('Design');
INSERT INTO area (name) VALUES ('Desenvolvimento de Software');
INSERT INTO area (name) VALUES ('Desenvolvimento Mobile');
INSERT INTO area (name) VALUES ('Desenvolvimento Web');
INSERT INTO area (name) VALUES ('Educação');
INSERT INTO area (name) VALUES ('Energia');
INSERT INTO area (name) VALUES ('Engenharia');
INSERT INTO area (name) VALUES ('Entretenimento');
INSERT INTO area (name) VALUES ('Farmácia');
INSERT INTO area (name) VALUES ('Finanças');
INSERT INTO area (name) VALUES ('Filosofia');
INSERT INTO area (name) VALUES ('Física');
INSERT INTO area (name) VALUES ('Gastronomia');
INSERT INTO area (name) VALUES ('Geologia');
INSERT INTO area (name) VALUES ('Gestão de Projetos');
INSERT INTO area (name) VALUES ('História');
INSERT INTO area (name) VALUES ('Hotelaria');
INSERT INTO area (name) VALUES ('Inovação');
INSERT INTO area (name) VALUES ('Internet das Coisas (IoT)');
INSERT INTO area (name) VALUES ('Jornalismo');
INSERT INTO area (name) VALUES ('Logística');
INSERT INTO area (name) VALUES ('Marketing');
INSERT INTO area (name) VALUES ('Marketing Digital');
INSERT INTO area (name) VALUES ('Medicina');
INSERT INTO area (name) VALUES ('Moda');
INSERT INTO area (name) VALUES ('Música');
INSERT INTO area (name) VALUES ('Nanotecnologia');
INSERT INTO area (name) VALUES ('Nutrição');
INSERT INTO area (name) VALUES ('Odontologia');
INSERT INTO area (name) VALUES ('Pesquisa e Desenvolvimento');
INSERT INTO area (name) VALUES ('Produtividade');
INSERT INTO area (name) VALUES ('Psicologia');
INSERT INTO area (name) VALUES ('Publicidade');
INSERT INTO area (name) VALUES ('Química');
INSERT INTO area (name) VALUES ('Realidade Aumentada (AR)');
INSERT INTO area (name) VALUES ('Realidade Virtual (VR)');
INSERT INTO area (name) VALUES ('Recursos Humanos');
INSERT INTO area (name) VALUES ('Recursos Naturais');
INSERT INTO area (name) VALUES ('Relações Internacionais');
INSERT INTO area (name) VALUES ('Relações Públicas');
INSERT INTO area (name) VALUES ('Saúde');
INSERT INTO area (name) VALUES ('Segurança');
INSERT INTO area (name) VALUES ('Segurança da Informação');
INSERT INTO area (name) VALUES ('Sustentabilidade');
INSERT INTO area (name) VALUES ('Tecnologia');
INSERT INTO area (name) VALUES ('Telecomunicações');
INSERT INTO area (name) VALUES ('Turismo');
INSERT INTO area (name) VALUES ('Vendas');
INSERT INTO area (name) VALUES ('Veterinária');